volumes: 
   mysql_data:
   redis_data:


services:
    mysql:
        image: mysql:8
        ports: 
             #coenctar mi puerto local 3306 al puerto 3306 el contenedor
             #Opcion 1 es lo siguiente
             #- 3306:3306
            - published: ${DEMO_MYSQL_PORT:-3306}
              target: 3306
        
        volumes: 
            #Montar el volumen o directorio de mysql_data en el contenedor esto es para guardar datos de la BD
            #se pueden utilizar variables de ambiente que esten en un archivo de .env
            - mysql_data:/var/lib/mysql

        environment: 
            MYSQL:USER: demo #root 
            MYSQL_PASSWORD: p4ssw0rd
            MYSQL_DATABASE: demo_development
            MYSQL_ROOT_PASSWORD: p4ssw0rd
    
    
    redis:
        image: redis:6-alpine
        ports: 
             #conectar mi puerto local -6379 al puerto -6379 el contenedor
             #Opcion 1 es lo siguiente
             #- 6379:6379
             - published: ${DEMO_REDIS_POTT:-6379}
               target: 6379
          
        volumes:
              #Montar el volumen o directorio de mysql_data en el contenedor esto es para guardar datos de la BD
              #se pueden utilizar variables de ambiente que esten en un archivo de .env
              - redis_data:/data
    
    mailhog:
        image: mailhog/mailhog:latest
        ports: 
            - published: ${DEMO_MAILHOG_PORT:-8025}
              target: 8025  

    
