services:
  mysql:
    environment:
      MYSQL_DATABASE: demo_development
      MYSQL_PASSWORD: omed
      MYSQL_ROOT_PASSWORD: omed
      MYSQL_USER: demo
    image: mysql:8
    ports:
      - ${DEMO_MYSQL_PORT:-3306}:3306
    volumes:
    - mysql_data:/var/lib/mysql:rw
  redis:
    image: redis:6-alpine
    ports:
      - ${DEMO_REDIS_PORT:-6379}:6379
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${DEMO_MAILHOG_PORT:-8025}:8025

version: '3.9'
volumes:
  mysql_data:
    driver: local
